name: Security Scan - CodeQL + Trivy

on:
  workflow_dispatch:

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t tammu431budda/githubactions:latest .

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tammu431budda/githubactions:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library

      - name: Upload Trivy scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Push image to Docker Hub
        if: success() # Only push if scan passes
        run: docker push tammu431budda/githubactions:latest
        
  codeql-scan:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t tammu431budda/githubactions:latest .

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'python'  # or 'javascript', etc.

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  gitleaks-scan:
    name: Secret Scan (Gitleaks)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2
